### ISSUE TITLE
square [ ] in mp3 filenames

### ISSUE THREAD

**Issue by sjlukacs** [Gordon999/Pi-MP3_Player#1]
hello one and all,

all of my mp3's have square brackets in mp3 filename.  it's where i have put the album name into the filename for 2 decades.

is that why when i Reload in the app, that none of my music is loaded into the ALLTracks.m3u playlist even though i have all of the music split out by artists under /media/pi/Music?

i mean wouldn't this work for Reloading the filelist:

from pathlib import Path
for f in Path("/media/pi/Music").glob("**/*.mp3"):
    print(f)

lucas

**Comment by Gordon999** [comment]
Sorry it's taken me a while to spot this !!
The square bracket issues seems to be a quirk in Python, l did mention it in the readme

"Avoid any directory/track names with [ ] (square brackets) in."

Did you get a fix ?

**Comment by Gordon999** [comment]
Assumed resolved
