### ISSUE TITLE
3.2" TFT SPI 240x320 display

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi-MP3_Player#2]
Thank you for the Beta version of the code which works (cutdown = 1) on the desktop monitor but struggling to make it work on the 3.2" TFT SPI display, any suggestions would be greatly appreciated, I have connected the display as in the pic....
![Raspberry pi TFT SPI display 240x320](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/189e6ec9-9394-4ef2-a88f-be4bef413bf7)
 also may I suggest a layout as 
![Acker Bilk Mod](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/5da9d67a-f882-401c-b223-c6e720698fee),
ie if there is an album pic then the "P-list, Artist, Album info will be hidden behind the cover pic and IF no album cover pic then it would 
look like below
![IMG_20240426_102925383_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/0ff10df8-e2b1-45e1-b0d7-7c5a7bdd1b93)

Thanks again

**Comment by Gordon999** [comment]
try latest version
![screen](https://github.com/Gordon999/Pi-MP3_Player/assets/15231212/6dd8cc30-92e7-45b1-933a-4adaafc8d303)

this may help ? https://bytesnbits.co.uk/retropie-raspberry-pi-0-spi-lcd/
or
https://raspberrypi.stackexchange.com/questions/120436/troubleshooting-rpi-4b-ili9341-display

Or

https://raspberrypi4u.blogspot.com/2014/12/raspberry-pi-connect-tft-lcd-with.html

**Comment by Gordon999** [comment]
I've been experimenting with a similar lcd , some progress but issues.
Only got it to work with Bookworm, but mp3 player won't show using tkinter, Bullseye won't work at all so far..

https://forums.raspberrypi.com/viewtopic.php?t=370089

**Comment by Gordon999** [comment]
An alternative l know works..

Buy one of these https://thepihut.com/products/spi-2-8-320x240-touch-screen-gpio?variant=20063171936318&currency=GBP&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&gad_source=1&gclid=Cj0KCQjwudexBhDKARIsAI-GWYWzDi1MCNyZdl0MGGmf2SRERW0EHrcmF2Vbhp65iwA6YmqiTtneLRkaAsc7EALw_wcB

Then using Bullseye..

git clone https://github.com/waveshare/LCD-show.git
cd LCD-show/
sudo ./LCD28-show

I would install all software using a hdmi monitor before running the above or you will be working on a small screen.
It will use cutdown 4 so l will modify to show images as per cutdown 1.

**Comment by Gordon999** [comment]
![IMG_20240504_145458](https://github.com/Gordon999/Pi-MP3_Player/assets/15231212/fdcb5ff4-65a5-41bd-a5fd-ad7ef1f4d9d6)
I finally got the ili9341 screen to work with BULLSEYE . (note no touchscreen).
Connections.

LCD---PI PIN (NOT GPIO NUMBER)
--
LED-------17(3.3v)
SCK-------23
SDI -------19
D/C-------15
RESET---13
CS---------24
GND------6 (gnd)
VCC------1 (3.3v)

Then ..

git clone https://github.com/waveshare/LCD-show.git
cd LCD-show/
sudo ./LCD28-show

I would install all software using a hdmi monitor before running the above or you will be working on a small screen.
It will use cutdown 4 so l will modify to show images as per cutdown 1.

**Comment by Gordon999** [comment]
Touchscreen now working using Bullseye RaspiOS... 

Calibrate touchscreen after connecting, Preferences > Calibrate Touchscreen
Follow instructions and 
save output to /usr/share/X11/xorg.conf.d/99-calibration.conf 

LCD---PI PIN (NOT GPIO NUMBER)
-----------------------------------
T_IRQ--------11
T_DO/OUT-21
T_DN/DIN-19*
T_CS-------26
T_CLK-----23^
SDO(MISO) N/C
LED--------1 (3.3v)
SCK--------23^
SDI---------19*
D/C---------15
RESET----13
CS----------24
GND--------6 (gnd)
VCC--------17 (3.3v)

Note 2 wires to PI pins 23 and 19
![lcd003](https://github.com/Gordon999/Pi-MP3_Player/assets/15231212/05b1fb59-418b-41b4-b012-928b8b375e4f)

**Comment by Gordon999** [comment]
Assumed solved

**Comment by Gordon999** [comment]
Closed

**Comment by Rich1975** [comment]
Sorry I didn't post sooner,
I was struggling to get the Inno-Maker RPI-HiFi-AMP (25watts) to work.
Have since figured it out . . .
1) create the microSD card
2) Install in to Raspberry pi, add dtoverlay=hifiberry-amp to the beginning of the /boot/config.txt
3) clone the waveshare program, cd to LCD-show and sudo ./LCD32-show .... since my display is 3.2"
4) waveshare software changed my config.txt file so I redid it (dtoverlay=hifiberry-amp)
5) then copied your software as per your instructions!
6) Googled how to remove the scrolling text when booting up

Next need to, or with you help make the cutdown=4 screen full screen without the deasktop showing all those item in the panel at the top and all the vacant space around, also the image is very light (like over exposed).
Thanks for all your help.

**Comment by Gordon999** [comment]
Can you upload an image of your screen. This is mine
![IMG_20240508_135039](https://github.com/Gordon999/Pi-MP3_Player/assets/15231212/cd0f89a4-7feb-46b9-88c1-0b6a2a7cfea3)


Regards the screen brightness it maybe down to the screen. You could try putting a resistor in series with the LED wire. Try 470ohms. I am looking into pwm control but it seems to give patterning issues.

**Comment by Rich1975** [comment]
![IMG_20240507_170938940_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/cf4fb065-3b3c-4200-9c86-327570567f71)

![IMG_20240508_065658830_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/454a036e-4b6e-444e-8a2e-7d904f61cce3)

![IMG_20240508_065709386_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/96a76814-b6b5-4569-9a2b-c573c26c14ae)

![IMG_20240508_065730064_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/a605e52e-2f96-4aad-b3ba-5d1293879c3b)

thanks , I don't have any resistors inline with the display

**Comment by Gordon999** [comment]
Try 4.7K ohms

**Comment by Gordon999** [comment]
Towards the end of the script find
elif cutdown == 4:
           root.geometry("520x320")
change to
elif cutdown == 4:
           root.geometry("480x320")

Does it remove the dead space ?

**Comment by Rich1975** [comment]
I'm planning to make this a self contained unit with built in rechargeable 12 v battery pack and as such I don't need the desktop showing, also, the Shutdn button doesn't really shut the unit off (total pwr off), the display is still lit, and I hear a slight noise from the speakers, both red leds are on for the pi and amp I will try your suggestion and edit the code and let you know.

**Comment by Gordon999** [comment]
Try the latest version...

**Comment by Rich1975** [comment]
Hi, I dont know what to make of this
comparing version 17.23 and version 17.24

![ver 17-23 b4 enter](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/a861e7df-96be-4a7a-8286-efbf5ea613b9)

**Comment by Rich1975** [comment]
Sorry pressed wrong button didnt mean to close

**Comment by Rich1975** [comment]
![ver 17-23 b4 enter](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/0a748f57-280e-49fc-884f-3621ee3d132b)

![ver 17-23 after enter](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/21e78f3f-7094-4ecc-9eb9-51e6db750185)   
Audio OK

and then no audio with ver 17.24

![ver 17-24 b4 enter](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/d66d314c-a791-45c4-b317-db1b8fb947f9)

![ver 17-24 after enter](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/06d301b0-f3a3-4048-8e45-a120db52b4e6)

**Comment by Gordon999** [comment]
It's setup to work on the small lcd, not a large screen. Set fullscreen = 0 for the large screen, or use another cutdown.

Please run this code on your small screen and tell me the result..

#!/usr/bin/env python3
from tkinter import *
root = Tk()
print(root.winfo_screenwidth(),root.winfo_screenheight())
root.destroy()

What resolution is your LG monitor ? What does it report with the above code ?

**Comment by Rich1975** [comment]
can't seem to get past this....

![Uploading 20240509_080047.jpg…]()

**Comment by Gordon999** [comment]
Your image is not showing

**Comment by Rich1975** [comment]
![IMG_20240509_083030680_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/b6b6762a-46ce-4f5f-ad7f-879630af6e62)

then I changed monitors to a smaller lg Model  Flatron E2281VRR not sure if that matters,
then changed code to Set fullscreen =0
then ran code version 17-23

![IMG_20240509_083556712_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/efa81ffa-748c-4507-8dcd-8350ba724c60)

and code version 17.24

![IMG_20240509_083627358_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/0af123f0-2a44-4d57-b765-7fc4042d93a6)

**Comment by Gordon999** [comment]
Can you save the above code as a .py file and run it.

**Comment by Rich1975** [comment]
wow! thanks to google also, I am new to this, but I found how to create the file and the result i 
656 416

**Comment by Gordon999** [comment]
Which screen is that ?

**Comment by Rich1975** [comment]
by "screen" you mean computer monitor? its a LG Flatron model E2281VR 
 PANEL SPECIFICATIONS
 Screen Size 22" Class (22.0" measured diagonally)
 Panel Type TN
 Aspect Ratio 16:9
 Resolution 1920 x 1080
 Brightness 250 cd/m2
 Contrast Ratio (DFC) 10,000,000:1
 Response Time 5 ms
 Viewing Angle (CR>10) 170º/160º
 Display Colors 16.7 M
 Panel Surface Anti-Glare, 3H
 FREQUENCY (H/V)
 Analog 30-83kHz/56-75Hz
 Digital 30-83kHz/56-75Hz
 FEATURES
 Super+ Resolution •
 PC •
 Video •
 Original Ratio •
 DDC/CI •
 HDCP •
 Auto Resolution •
 Tiling •
 Plug & Play DDC2B
etc...

or the project display? 
its a 3.2" SPI display

**Comment by Gordon999** [comment]
I need the numbers for the spi 3.2" screen from the code

**Comment by Rich1975** [comment]
I'm assuming that those numbers after running the code was for the spi 3.2" screen, that's what shows up on the computer screen, I'm not sure how to get it any other way
656 416

**Comment by Gordon999** [comment]
OK. Just a bit surprising, mine shows 480 320.

**Comment by Gordon999** [comment]
let me know what v17.25 does

**Comment by Rich1975** [comment]
The raspberry pi with the audio hat and 3.2 spi display are hooked up to a computer monitor, I then turned power on, after bootup I see the opening screen for the OS, I then open a terminal and type in python3 screen.py  (which it the file name I gave to save the code you gave) and the results I'm assuming are for the 3.2 spi display NOT the computer monitor.
I do have another 3.2 spi display (long ago that's how they sold them ... in 2s) which i can swap out and let you know the results

**Comment by Rich1975** [comment]
The other screen shows 656 416 also,
Ok, I'll download and run v17.25 and let you know

**Comment by Rich1975** [comment]
![IMG_20240509_120926147_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/65780578-4c2e-47e1-961d-f6c103270831)

Goes directly into full screen mode, audio is ok but has all that blank space around

**Comment by Gordon999** [comment]
What's it like on the 3.2" spi screen ?

**Comment by Rich1975** [comment]
![IMG_20240509_133052642_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/6ad26029-182b-460b-920f-163eb4a7b69c)

**Comment by Gordon999** [comment]
ok give me a while to look at this.

Can you confirm you are using Bullseye, spi screen wired as l showed, installed using...

git clone https://github.com/waveshare/LCD-show.git
cd LCD-show/
sudo ./LCD28-show

do you have a section like this in /boot/config.txt ?
dtoverlay=waveshare32b:rotate=270
hdmi force hotplug=1
hdmi group =2
hdmi mode=1
hdmi mode=87
hdmi cvt 480 320 25 6 0 0 0

How are you swapping between spi and hdmi monitor ? Different sd cards?

Please try v17.26, it uses cutdown=2 to hopefully match your screen

**Comment by Rich1975** [comment]
Hi,
Yes I'm using Bullseye, spi, screen, wired as shown
Downloaded waveshare/LCD-show 
cd LCD-show/
here is where I changed , instead  "sudo ./LCD32-show" since my display is  3.2 inches as I mentioned in some earlier comments. which is no problem I can redo the waveshare part.
See the pic of the contents of my config.txt file

![IMG_20240510_060901820_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/12976c3b-4623-48f7-a996-fa15eef3ac34)

If I change as per your suggestion I can no longer see images on my computer monitor,
because, my Raspberry pi is hooked up directly to my Computer monitor HDMI and my keyboard/mouse to USB.
on another note I have found that changing cutdown 4 "self.length =36 to 60 and then changing the width and height of some of the buttons I can rearrange the screen to fit.  (width = 10 and height = 4), Would that be ok?

**Comment by Gordon999** [comment]
I see whats happening !!

Your config is setting a different hdmi mode to mine and giving the 656 x 416 resolution.
I didn't realise you could get the spi and hdmi to both work at the same time, very useful. Where did you get the settings from ?

Try v17.26, it should fill the screen with cutdown=2

If you prefer cutdown=4 I can modify to suit

**Comment by Rich1975** [comment]
I actually prefer v17.26 layout, thanks, there is still a slight space on the right side so I will try changing the values of the buttons to center the image.
Thanks ever so much for helping me, I've learned so much at my old age😊. When I do complete this project I will send you a picture.

**Comment by Gordon999** [comment]
Let me know your changes when you've done them. It was based on 640x480 but changed to 656x416 hence the right hand space.

**Comment by Rich1975** [comment]
Sure will, so, do you think I will be able to adjust the display or am i wasting my time?

**Comment by Gordon999** [comment]
Just experiment with the sizes in cutdown=2  section, starting line 606

self.Disp_plist_name = tk.Label(self.Frame10, height=1, width=44...
Try increasing the width for artist,album and track to 46

**Comment by Gordon999** [comment]
I have uploaded v17.28. It should centre the image for cutdown=2 if using 656x416.

It will be better to modify your config.txt to control the image size eg..

dtoverlay=waveshare32b:rotate=270
hdmi force hotplug=1
hdmi group =2
hdmi mode=87
hdmi cvt 640 480 60 6 0 0 0

Will give a 640x480 image and should work on both hdmi monitor and spi screen
The script will adjust the layout between 640x480 and 656x416 to suit cutdown=2

**Comment by Rich1975** [comment]
![IMG_20240511_092436816](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/028e2b3b-cec3-440b-9c69-661a9f44f727)

the 1 thing I noticed is that the text for some of the buttons may be too large to fit inside, may be reduce it,  I noticed also that pause, sleep shutdown some times does not exit the script

**Comment by Gordon999** [comment]
Play needs to be stopped, then SHUFFLE , then SLEEP then SHUTDOWN, to exit.

I'll look at the font size.

**Comment by Gordon999** [comment]
v17.30 fonts fixed in cutdown=2

I think l have solved the issues with the spi screen, so l will close this.
Any other issues please open new issues. Thanks.

**Comment by Gordon999** [comment]
Closed
