### ISSUE TITLE
LCD dimming

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi-MP3_Player#3]
Thanks for v17-30 it works for me,
Line 91 in the code "self.LCD_LED_pin =14      # LCD backlight GPIO"
I don't have it connected, instead I have a 4.7k resistor from LED pin on the display connected to 3.3v on the pi (physical pin 1). the 4.7k resistor hasn't made much difference, may be a higher value?

**Comment by Gordon999** [comment]
There is the option to connect the LED wire to a gpio for blanking. But there maybe issues as it needs the script running to see anything on the screen at boot unless you choose something like pin 8 ( gpio 14) which has a pullup.
You could get the script to autostart at boot (  add @/usr/bin/python3 /home/pi/MP3_Player.py to the end of /etc/xdg/lxsession/LXDE-pi/autostart ) and use another gpio output.
Try increasing the resistor but l still find the screen varies a bit in brightness, not a script issue. You still need a resistor with any gpio for the LED output, the output is only on or off, not pwm as l found that patterns.

**Comment by Gordon999** [comment]
Please try v17.31.
connect the LED wire to gpio 18 (pin12)

add the following line to /boot/config.txt
dtoverlay=gpio-poweroff,gpiopin=18,active_low

 Then reboot the pi

It now should blank and light the spi screen as appropriate at boot, timeout, exit, shutdown etc

v17.32 should work similarly but uses PWM for the LED. You can experiment with levels for self.bright (on) and self.dim (off)

**Comment by Rich1975** [comment]
Hi, It does blank the display and on the computer screen I see text regarding the shutting down etc and then for a second it flashes some text and goes dark again, but the biggest problem for me is that I lose audio. Here's what I do....
1, turn on, and in terminal mode I select v17.30 to play, sound is OK, I exit it (X)  and then load v17.32 and press play, no audio!

**Comment by Gordon999** [comment]
How is your audio connected? Do you know which gpios your amp uses ?

**Comment by Rich1975** [comment]
Even removing the line "dtoverlay =gpio-poweroff,gpiopin=18,active_low" rebooting doesn't help bring back the audio in v17-32

**Comment by Rich1975** [comment]
I have Inno-Maker HIFiberry hat (25 watts) plugged directly on top of the raspberry pi 3 A+

**Comment by Gordon999** [comment]
Looks like it uses gpio 18, pin12 !!

I'll need to move LED cable
![IMG_20240514_174134](https://github.com/Gordon999/Pi-MP3_Player/assets/15231212/f9013cc3-7350-4925-9bef-589b8e21171d)

**Comment by Gordon999** [comment]
Please try v17.33.
connect the LED wire to gpio 23 (pin16)

change the following line in /boot/config.txt
dtoverlay=gpio-poweroff,gpiopin=18,active_low
To
dtoverlay=gpio-poweroff,gpiopin=23,active_low

Then reboot the pi

**Comment by Rich1975** [comment]
Hi, I did as you recommended with the 4.7k resistor in series connecting the LED pin on the display to pin physical pin 16 on the pi,  added the line dtoverlay=gpio-poweroff,gpiopin=23,active_low in/boot/config.txt, set up to start automatically GUI and the pi boots up and just before the actual player screen shows up, the desktop  show up, about 2 seconds, within that time I can click on the folders icon or the terminal icon to make any changes like add songs etc, if I miss that time the player screen shows up in full screen mode (v17.33) , the exit to desktop mode (stop, pause, sleep, shutdown does not work it just shuts down, then I have to turn off the power and try again!

**Comment by Gordon999** [comment]
It's stop playing, **shuffle**,sleep, shutdown not pause

**Comment by Gordon999** [comment]
v17.36 added self.Shutdown_exit setting.
when set to 0 the shutdown button will NOT shutdown the Pi.
when set to 1 the shutdown button will shutdown the Pi, unless you stop playing, set shuffle,set sleep, click shutdown, then it will exit and not shutdown.

Also added that if you use a mouse ***right*** click on SHUTDOWN will exit but not shutdown, ***left*** click action will depend on self.Shutdown_exit, set to 0 it won't shutdown, if set to 1 it will SHUTDOWN UNLESS you have stopped playing, set shuffle & set sleep as above.

**Comment by Rich1975** [comment]
Hi, I made some changes to the layout of the screen for v34-cutdown 2 since I saw some extra space on the right side 
![IMG_20240517_083134596_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/6dbedf3d-99c5-4ecd-a0b5-d4babae8dcc2)

In the code line 548 vol> changed width=5 to 6 etc all the way down and the also the progress par moved

**Comment by Gordon999** [comment]
OK.  Updates added to v17.38

**Comment by Rich1975** [comment]
Hi, Thanks for all your help !, Here are pics of my completed project, showed it to my siblings and the requests to build something for them are coming in... may be the 5 button 20 x 4 line display is next !
![IMG_20240614_220815752_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/1bee3b63-1b6e-4a91-a759-07e28707eeef)

![IMG_20240614_220747893_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/ef878b85-8a98-4bbf-b56f-29b7473565da)

![IMG_20240614_220652544_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/264c46e4-e4d7-4ebf-969f-03bc5db45f3b)

![IMG_20240614_220610603_HDR](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/22775349-8d14-40ab-8229-8977ed648760)
