### ISSUE TITLE
5 inch display

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi-MP3_Player#4]
Hi, by any chance the 5" Elecrow Touch screen MPI500 display a viable alternate to the 3.5" screen.
Everything is plugged in and works except that the image is too small to fill the screen.
Thanks

Specifications
5.0" TFT LCD Module
Resolution:800x400
Touch Screen Type: Resistive
LCD driver IC: ILI9486L
Refresh rate: 60Hz
LCD Size: 121.11mm*77.93mm
HDMI connection

Hareware Description
1.Micro USB: get 5V power (not need when connect by GPIO)
2.HD interface: Audio/video transmission
3.Backlight switch: turn on/off the backlight (save power)
4.GPIO (13*2): get 5V power& touch function
![image](https://github.com/Gordon999/Pi-MP3_Player/assets/65562141/7a364acb-44ee-4402-b308-fae92ccc23e2)

**Comment by Gordon999** [comment]
Try changing to cutdown  = 0, or 5 or 6 or 7

#set display format
0 800x480
5 800x480 SIMPLE LAYOUT,only default Playlist
6 800x480 List 10 tracks
7 800x480 with scrollbars
