### ISSUE TITLE
Font size in cutdown 5

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi-MP3_Player#5]
Hi, Giving up on 5 button MP3 player I am hoping to get some help in increasing the font size for cutdown 5, the simple layout, being that there is so much space on each icon, for the sight impaired it would be nice to increase the font size, if you help me with some directions I would gladly modify the script! Changing line 854 in the code "font = 60" to a higher of lower number doesn't help, how about line 853 "self length = 60" ? 
Thanks Richard

**Comment by Rich1975** [comment]
Hope this helps

![IMG_20240921_184237859_HDR](https://github.com/user-attachments/assets/32c5b3ba-acb5-4b6f-9c3e-bbb592a7a3da)

**Comment by Gordon999** [comment]
try the latest version...

Changing font sizes in tkinter can be a bit of a hassle as it also changes button sizes etc...

![screen5](https://github.com/user-attachments/assets/68e725f7-9c09-4931-83fb-d4f54bc3c156)

**Comment by Gordon999** [comment]
Regards your 5 button issue try 5B_LCD_MP3_Player2.py, as the backlight in the original version maybe stopped the 25W amp audio. Disconnect any wire you had on pin40, and put the link back on the lcd pcb, if you ever removed it !

If there are issues with the backlight not working try 5B_LCD_MP3_Player.py v1.3 where the backlight has moved to pin 38

**Comment by Gordon999** [comment]
Assumed resolved...
