### ISSUE TITLE
Album or Track titles > 50 chars will scroll.

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi-MP3_Player#6]
Hi,
Is this option available for cutdown 5 also?
I am using a 5" capacitive HDMI touch screen from ELECROW  (800x480 pixel) and a Raspberry Pi3B+
Thank you

**Comment by Gordon999** [comment]
Try changing line 891 to self.length = 25

Did you get the 5button LCD player to work with the innomaker amp ? I think l fixed it in the latest code.

**Comment by Rich1975** [comment]
Sorry for the delay in replying about audio thru the Innomaker amp, no, it still does not work, though using VLC from the Raspberry Pi 2W desktop I ca get audio!
Another thing I noticed was that to get it to AutoStart I had to follow the directions for Pi-MP3_Player ie create a myscript.sh file etc...

Including a pic of my completed MP3 player using a Raspberry pi 3b+, Innomaker Hifiberry amp, a couple of speakers from a used TV AND your great program which you helped me with...
![IMG_20241118_182058931_HDR](https://github.com/user-attachments/assets/33c43eaf-babb-472c-88b5-7d96346716ac)
 I do have the parts for the 5button MP3 Player but probably wont complete the construction, may just dab with it, trying different things
Thanks for all your help

**Comment by Gordon999** [comment]
Pleased you have this working. I'll keep investigating the innomaker amp issue.

Autostart using /etc/xdg../autostart will not work with Bookworm unless you switch to X11

I assume scrolling is working

**Comment by Gordon999** [comment]
I have bought and fitted an innomaker 25W amp hat and it works fine with Pi_5B_LCD_MP3_Player2.py

I added dtoverlay=hifiberry-amp to /boot/firmware/config.txt

using pi4, bookworm 64bit full version, 12v psu

See https://github.com/Gordon999/Pi_5B_LCD_MP3_Player/issues/2
